
CREATE TABLE CSV1 (
	idCSV1 INTEGER IDENTITY(0,1) NOT NULL PRIMARY KEY,
	Boletim VARCHAR(255),
	DataHoraBoletim DATETIME,
	Sequencial INTEGER,
	idCategoria INTEGER FOREIGN KEY REFERENCES dCATEGORIA(idCategoria),
	idEspecie INTEGER FOREIGN KEY REFERENCES dESPECIE(idEspecie),
	idSituacao INTEGER FOREIGN KEY REFERENCES dSITUACAO(idSituacao),
	idSocorro INTEGER FOREIGN KEY REFERENCES dSOCORRO(idSocorro)
);