
CREATE TABLE CSV2 (
	idCSV2 INTEGER IDENTITY(0,1) NOT NULL PRIMARY KEY,
	Boletim VARCHAR(255),
	DataHoraBoletim DATETIME,
	DataHoraInclusao DATETIME,
	idTipoAcidente INTEGER FOREIGN KEY REFERENCES dTIPOACIDENTE(idTipoAcidente),
	idClima INTEGER FOREIGN KEY REFERENCES dCLIMA(idCLima),
	idPavimento INTEGER FOREIGN KEY REFERENCES dPAVIMENTO(idPavimento),
	idRegional INTEGER FOREIGN KEY REFERENCES dREGIONAL(idRegional),
	idOrigemBoletim INTEGER FOREIGN KEY REFERENCES dORIGEMBOLETIM(idOrigemBoletim),
	idSinalizado INTEGER FOREIGN KEY REFERENCES dSINALIZADO(idSinalizado),
	idVelocidade INTEGER FOREIGN KEY REFERENCES dVELOCIDADE(idVelocidade),
	CoordenadaX VARCHAR(255),
	CoordenadaY VARCHAR(255),
	idHoraInformada INTEGER FOREIGN KEY REFERENCES dHORAINFORMADA(idHoraInformada),
	idFatalidade INTEGER FOREIGN KEY REFERENCES dFATALIDADE(idFatalidade),
	idSeveridade INTEGER FOREIGN KEY REFERENCES dSEVERIDADE(idSeveridade)
);