
CREATE TABLE CSV4 (
	idCSV4 INTEGER IDENTITY(0,1) NOT NULL PRIMARY KEY,
	Boletim VARCHAR(255),
	DataHoraBoletim DATETIME,
	Sequencial INTEGER,
	idCondutor INTEGER FOREIGN KEY REFERENCES dCONDUTOR(idCondutor),
	idSeveridade INTEGER FOREIGN KEY REFERENCES dSEVERIDADE(idSeveridade),
	idSexo INTEGER FOREIGN KEY REFERENCES dSEXO(idSexo),
	idCintoSeguranca INTEGER FOREIGN KEY REFERENCES dCINTOSEGURANCA(idCintoSeguranca),
	idEmbriaguez INTEGER FOREIGN KEY REFERENCES dEMBRIAGUEZ(idEmbriaguez),
	DataNascimento DATE,
	idHabilitacao INTEGER FOREIGN KEY REFERENCES dHABILITACAO(idHabilitacao),
	idEspecie INTEGER FOREIGN KEY REFERENCES dESPECIE(idEspecie),
	idPedestre INTEGER FOREIGN KEY REFERENCES dPEDESTRE(idPedestre),
	idPassageiro INTEGER FOREIGN KEY REFERENCES dPASSAGEIRO(idPassageiro)
);