
-- Crie da tabela

CREATE TABLE dTEMPO( 
IDTEMPO INT IDENTITY NOT NULL PRIMARY KEY,
DATA DATE NOT NULL,
ANO SMALLINT NOT NULL,
MES SMALLINT NOT NULL,
DIA SMALLINT NOT NULL,
DIA_SEMANA SMALLINT NOT NULL,
DIA_ANO SMALLINT NOT NULL,
ANO_BISSEXTO CHAR(1) NOT NULL,
DIA_UTIL CHAR(1) NOT NULL,
FIM_SEMANA CHAR(1) NOT NULL,
FERIADO CHAR(1) NOT NULL,
PRE_FERIADO CHAR(1) NOT NULL,
POS_FERIADO CHAR(1) NOT NULL,
NOME_FERIADO VARCHAR(30) NULL,
NOME_DIA_SEMANA VARCHAR(15) NOT NULL,
NOME_DIA_SEMANA_ABREV CHAR(3) NOT NULL,
NOME_MES VARCHAR(15) NOT NULL,
NOME_MES_ABREV CHAR(3) NOT NULL,
QUINZENA SMALLINT NOT NULL,
BIMESTRE SMALLINT NOT NULL,
TRIMESTRE SMALLINT NOT NULL,
SEMESTRE SMALLINT NOT NULL,
NR_SEMANA_MES SMALLINT NOT NULL,
NR_SEMANA_ANO SMALLINT NOT NULL,
ESTACAO_ANO VARCHAR(15) NOT NULL,
DATA_POR_EXTENSO VARCHAR(50) NOT NULL,
EVENTO VARCHAR(50) NULL)

-- Declare as variáveis

DECLARE
@DATAINICIAL DATE,
@DATAFINAL DATE,
@DATA DATE, 
@ANO SMALLINT,
@MES SMALLINT,
@DIA SMALLINT, 
@DIASEMANA SMALLINT,
@DIAUTIL CHAR(1),
@FIMSEMANA CHAR(1), 
@FERIADO CHAR(1),
@PREFERIADO CHAR(1),
@POSFERIADO CHAR(1), 
@NOMEFERIADO VARCHAR(30),
@NOMEDIASEMANA VARCHAR(15), 
@NOMEDIASEMANAABREV CHAR(3),
@NOMEMES VARCHAR(15), 
@NOMEMESABREV CHAR(3),
@BIMESTRE SMALLINT,
@TRIMESTRE SMALLINT, 
@NRSEMANAMES SMALLINT,
@ESTACAOANO VARCHAR(15), 
@DATAPOREXTENSO VARCHAR(50)

-- Defina a datas inicial e final do período desejado

SET @DATAINICIAL = '01/01/2011'
SET @DATAFINAL = '31/12/2019'

WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
	SET @DATA = @DATAINICIAL
	SET @ANO = YEAR(@DATA)
	SET @MES = MONTH(@DATA)
	SET @DIA = DAY(@DATA)
	SET @DIASEMANA = DATEPART(WEEKDAY,@DATA)

IF @DIASEMANA IN (1,7) 
SET @FIMSEMANA = 'S'
ELSE SET @FIMSEMANA = 'N'

 -- Declare os feriados locais e regionais.
 -- Declare aqueles que também não possuem data fixa (Carnaval, Páscoa e Corpus Christi também)

IF (@MES = 1 AND @DIA IN (1,2)) OR (@MES = 12 AND @DIA = 31) --Feriado de Confraternização Universal
SET @NOMEFERIADO = 'CONFRATERNIZAÇÃO UNIVERSAL'
ELSE 
IF (@MES = 4 AND @DIA IN (20,21,22)) -- Feriado de Tiradentes
SET @NOMEFERIADO = 'TIRADENTES'
ELSE 
IF (@MES = 5 AND @DIA IN (1,2))OR (@MES = 4 AND @DIA = 30) -- Feriado do Dia do Trabalhador
SET @NOMEFERIADO = 'DIA DO TRABALHO'
ELSE 
IF (@MES = 9 AND @DIA IN (6,7,8)) -- Feriado da Independência do Brasil
SET @NOMEFERIADO = 'INDEPENDÊNCIA DO BRASIL'
ELSE 
IF (@MES = 10 AND @DIA IN (11,12,13)) -- Feriado de Nossa Senhora Aparecida
SET @NOMEFERIADO = 'NOSSA SENHORA APARECIDA'
ELSE
IF (@MES = 11 AND @DIA IN (1,2,3)) -- Feriado de Finados
SET @NOMEFERIADO = 'FINADOS'
ELSE
IF (@MES = 11 AND @DIA IN (14,15,16)) -- Feriado de Proclamação da República
SET @NOMEFERIADO = 'PROCLAMAÇÃO DA REPÚBLICA'
ELSE
IF (@MES = 12 AND @DIA IN (24,25,26)) -- Natal
SET @NOMEFERIADO = 'NATAL'
ELSE SET @NOMEFERIADO = NULL

IF (@MES = 12 AND @DIA = 31) OR --CONFRATERNIZAÇÃO UNIVERSAL
(@MES = 4 AND @DIA = 20) OR --TIRADENTES
(@MES = 4 AND @DIA = 30) OR --DIA DO TRABALHO
(@MES = 9 AND @DIA = 6) OR --INDEPENDÊNCIA DO BRASIL
(@MES = 10 AND @DIA = 11) OR --NOSSA SENHORA APARECIDA
(@MES = 11 AND @DIA = 1) OR --FINADOS
(@MES = 11 AND @DIA = 14) OR --PROCLAMAÇÃO DA REPÚBLICA
(@MES = 12 AND @DIA = 24) --NATAL
SET @PREFERIADO = 'S'
ELSE SET @PREFERIADO = 'N'

IF (@MES = 1 AND @DIA = 1) OR --CONFRATERNIZAÇÃO UNIVERSAL
(@MES = 4 AND @DIA = 21) OR --TIRADENTES
(@MES = 5 AND @DIA = 1) OR --DIA DO TRABALHO
(@MES = 9 AND @DIA = 7) OR --INDEPENDÊNCIA DO BRASIL
(@MES = 10 AND @DIA = 12) OR --NOSSA SENHORA APARECIDA
(@MES = 11 AND @DIA = 2) OR --FINADOS
(@MES = 11 AND @DIA = 15) OR --PROCLAMAÇÃO DA REPÚBLICA
(@MES = 12 AND @DIA = 25) --NATAL
SET @FERIADO = 'S'
ELSE SET @FERIADO = 'N'

IF (@MES = 1 AND @DIA = 2) OR --CONFRATERNIZAÇÃO UNIVERSAL
(@MES = 4 AND @DIA = 22) OR --TIRADENTES
(@MES = 5 AND @DIA = 2) OR --DIA DO TRABALHO
(@MES = 9 AND @DIA = 8) OR --INDEPENDÊNCIA DO BRASIL
(@MES = 10 AND @DIA = 13) OR --NOSSA SENHORA APARECIDA
(@MES = 11 AND @DIA = 3) OR --FINADOS
(@MES = 11 AND @DIA = 16) OR --PROCLAMAÇÃO DA REPÚBLICA
(@MES = 12 AND @DIA = 26) --NATAL
SET @POSFERIADO = 'S'
ELSE SET @POSFERIADO = 'N'

SET @NOMEMES = CASE WHEN @MES = 1 THEN 'JANEIRO'
WHEN @MES = 2 THEN 'FEVEREIRO'
WHEN @MES = 3 THEN 'MARÇO'
WHEN @MES = 4 THEN 'ABRIL'
WHEN @MES = 5 THEN 'MAIO'
WHEN @MES = 6 THEN 'JUNHO'
WHEN @MES = 7 THEN 'JULHO'
WHEN @MES = 8 THEN 'AGOSTO'
WHEN @MES = 9 THEN 'SETEMBRO'
WHEN @MES = 10 THEN 'OUTUBRO'
WHEN @MES = 11 THEN 'NOVEMBRO'
WHEN @MES = 12 THEN 'DEZEMBRO' END

SET @NOMEMESABREV = CASE WHEN @MES = 1 THEN 'JAN'
WHEN @MES = 2 THEN 'FEV'
WHEN @MES = 3 THEN 'MAR'
WHEN @MES = 4 THEN 'ABR'
WHEN @MES = 5 THEN 'MAI'
WHEN @MES = 6 THEN 'JUN'
WHEN @MES = 7 THEN 'JUL'
WHEN @MES = 8 THEN 'AGO'
WHEN @MES = 9 THEN 'SET'
WHEN @MES = 10 THEN 'OUT'
WHEN @MES = 11 THEN 'NOV'
WHEN @MES = 12 THEN 'DEZ' END

IF @FIMSEMANA = 'S' OR @FERIADO = 'S'
SET @DIAUTIL = 'N'
ELSE SET @DIAUTIL = 'S'

SET @NOMEDIASEMANA = CASE WHEN @DIASEMANA = 1 THEN 'DOMINGO'
WHEN @DIASEMANA = 2 THEN 'SEGUNDA-FEIRA'
WHEN @DIASEMANA = 3 THEN 'TERÇA-FEIRA'
WHEN @DIASEMANA = 4 THEN 'QUARTA-FEIRA'
WHEN @DIASEMANA = 5 THEN 'QUINTA-FEIRA'
WHEN @DIASEMANA = 6 THEN 'SEXTA-FEIRA'
ELSE 'SÁBADO' END

SET @NOMEDIASEMANAABREV = CASE WHEN @DIASEMANA = 1 THEN 'DOM'
WHEN @DIASEMANA = 2 THEN 'SEG'
WHEN @DIASEMANA = 3 THEN 'TER'
WHEN @DIASEMANA = 4 THEN 'QUA'
WHEN @DIASEMANA = 5 THEN 'QUI'
WHEN @DIASEMANA = 6 THEN 'SEX'
ELSE 'SÁB' END

SET @BIMESTRE = CASE WHEN @MES IN (1,2) THEN 1
WHEN @MES IN (3,4) THEN 2
WHEN @MES IN (5,6) THEN 3
WHEN @MES IN (7,8) THEN 4
WHEN @MES IN (9,10) THEN 5
ELSE 6 END

SET @TRIMESTRE = CASE WHEN @MES IN (1,2,3) THEN 1
WHEN @MES IN (4,5,6) THEN 2
WHEN @MES IN (7,8,9) THEN 3
ELSE 4 END

SET @NRSEMANAMES = (DAY(@DATAINICIAL) + (DATEPART(DW, DATEADD (MONTH, DATEDIFF (MONTH, 0, @DATAINICIAL), 0))-1)	-1)/7 + 1

IF @DATA BETWEEN CAST('23/09/'+CONVERT(CHAR(4),@ANO) AS DATE) AND CAST('20/12/'+CONVERT(CHAR(4),@ANO) AS DATE)
SET @ESTACAOANO = 'PRIMAVERA'
ELSE IF @DATA BETWEEN CAST('21/03/'+CONVERT(CHAR(4),@ANO) AS DATE) AND CAST('20/06/'+CONVERT(CHAR(4),@ANO) AS DATE)
SET @ESTACAOANO = 'OUTONO'
ELSE IF @DATA BETWEEN CAST('21/06/'+CONVERT(CHAR(4),@ANO) AS DATE) AND CAST('22/09/'+CONVERT(CHAR(4),@ANO) AS DATE)
SET @ESTACAOANO = 'INVERNO'
ELSE -- @DATA BETWEEN 21/12 E 20/03
SET @ESTACAOANO = 'VERÃO'

INSERT INTO dTEMPO
SELECT @DATA
,@ANO
,@MES
,@DIA
,@DIASEMANA
,DATEPART(DAYOFYEAR,@DATA)
,CASE WHEN (@ANO % 4) = 0 THEN 'S' ELSE 'N' END -- Verifica se o ano é bissexto
,@DIAUTIL
,@FIMSEMANA
,@FERIADO
,@PREFERIADO
,@POSFERIADO
,@NOMEFERIADO
,@NOMEDIASEMANA
,@NOMEDIASEMANAABREV
,@NOMEMES
,@NOMEMESABREV
,CASE WHEN @DIA < 16 THEN 1 ELSE 2 END -- Verifica a quinzena (primeira ou segunda)
,@BIMESTRE
,@TRIMESTRE
,CASE WHEN @MES < 7 THEN 1 ELSE 2 END -- Verifica o semestre (primeiro ou segundo)
,@NRSEMANAMES
,DATEPART(WK,@DATA) -- Verifica o número da semana
,@ESTACAOANO
,LOWER(@NOMEDIASEMANA + ', ' + CAST(@DIA AS VARCHAR) + ' DE ' + @NOMEMES + ' DE ' + CAST(@ANO AS VARCHAR))

SET @DATAINICIAL = DATEADD(DAY,1,@DATAINICIAL) 
END