
-- Criação da tabela

CREATE TABLE FATO2 (
    Boletim VARCHAR(255) NOT NULL,
	DataHoraBoletim DATETIME NOT NULL,
	DataHoraInclusao DATETIME NOT NULL,
	Sequencial INTEGER NOT NULL,
	idTipoAcidente INTEGER FOREIGN KEY REFERENCES dTIPOACIDENTE(idTipoAcidente),
	idClima INTEGER FOREIGN KEY REFERENCES dCLIMA(idClima),
	idPavimento INTEGER FOREIGN KEY REFERENCES dPAVIMENTO(idPavimento),
	idRegional INTEGER FOREIGN KEY REFERENCES dREGIONAL(idRegional),
	idOrigemBoletim INTEGER FOREIGN KEY REFERENCES dORIGEMBOLETIM(idOrigemBoletim),
	idSinalizado INTEGER FOREIGN KEY REFERENCES dSINALIZADO(idSinalizado),
	idVelocidade INTEGER FOREIGN KEY REFERENCES dVELOCIDADE(idVelocidade),
	idHoraInformada INTEGER FOREIGN KEY REFERENCES dHORAINFORMADA(idHoraInformada),
	idFatalidade INTEGER FOREIGN KEY REFERENCES dFATALIDADE(idFatalidade),
	idSeveridade INTEGER FOREIGN KEY REFERENCES dSEVERIDADE(idSeveridade),
	idCondutor INTEGER FOREIGN KEY REFERENCES dCONDUTOR(idCondutor),
	idSexo INTEGER FOREIGN KEY REFERENCES dSEXO(idSexo),
	idCintoSeguranca INTEGER FOREIGN KEY REFERENCES dCINTOSEGURANCA(idCintoSeguranca),
	idEmbriaguez INTEGER FOREIGN KEY REFERENCES dEMBRIAGUEZ(idEmbriaguez),
	idHabilitacao INTEGER FOREIGN KEY REFERENCES dHABILITACAO(idHabilitacao),
	idPedestre INTEGER FOREIGN KEY REFERENCES dPEDESTRE(idPedestre),
	idPassageiro INTEGER FOREIGN KEY REFERENCES dPASSAGEIRO(idPassageiro),
	DataNascimento DATE,
	CoordenadaX VARCHAR(255),
	CoordenadaY VARCHAR(255),
	PRIMARY KEY (Boletim, DataHoraBoletim, DataHoraInclusao, Sequencial)
);